package com.company;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static java.lang.Thread.sleep;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TestAuthentificationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private long timer = 2000;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAuthentification() throws InterruptedException {
    driver.get("https://outlook.live.com/owa/");
    driver.manage().window().setSize(new Dimension(1060, 815));
    sleep(timer);
    driver.findElement(By.linkText("Войти")).click();
    sleep(timer);
    driver.findElement(By.id("i0116")).sendKeys("alexandr.bonta@outlook.com");
    sleep(timer);
    driver.findElement(By.id("i0116")).sendKeys(Keys.ENTER);
    sleep(timer);
    driver.findElement(By.id("i0118")).sendKeys("#####");
    sleep(timer);
    driver.findElement(By.id("i0118")).sendKeys(Keys.ENTER);
    {
      sleep(timer);
      WebElement element = driver.findElement(By.cssSelector(".\\_2KqWkae0FcyhdNhWQ-Cp-M > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".\\_2KqWkae0FcyhdNhWQ-Cp-M > img")).click();
    {
      sleep(timer);
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      sleep(timer);
      WebElement element = driver.findElement(By.id("mectrl_headerPicture"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      sleep(timer);
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    sleep(timer);
    driver.findElement(By.id("mectrl_body_signOut")).click();
  }
}
